import type {Metadata} from "next";
import 'bootstrap/dist/css/bootstrap.min.css';
import 'admin-lte/dist/css/adminlte.min.css';

import {Inter} from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Sidebar from "@/components/Sidebar";
import Script from 'next/script';
import ContentHeader from "@/components/ContentHeader";
import Footer from "@/components/Footer";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(
  {
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>) {

  return (
    <html lang="en">
    <head>
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fontsource/source-sans-3@5.0.12/index.css"
            integrity="sha256-tXJfXfp6Ewt1ilPzLDtQnJV4hclT9XuaZUKyUvmyr+Q=" crossOrigin="anonymous"/>
      <link rel="stylesheet"
            href="https://cdn.jsdelivr.net/npm/overlayscrollbars@2.3.0/styles/overlayscrollbars.min.css"
            integrity="sha256-dSokZseQNT08wYEWiz5iLI8QPlKxG+TswNRD8k35cpg=" crossOrigin="anonymous"/>
      <link rel="stylesheet"
            href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.0/font/bootstrap-icons.min.css"
            integrity="sha256-Qsx5lrStHZyR9REqhUF8iQt73X06c8LGIUPzpOhwRrI=" crossOrigin="anonymous"/>
      <script src="https://code.jquery.com/jquery-3.7.1.min.js"
              integrity="sha384-ZrZ3os5FBmQXVDUq0eBDjgmEn1PrKPa2U2s2a6VDz4ylBHTM8sCk2DNPzXvFadjp"
              crossOrigin="anonymous"/>
      <script src="https://cdn.datatables.net/2.0.8/js/dataTables.bootstrap5.min.js"
              integrity="sha384-n/Siy80bh6IvkoKxaPtMj+p9lqwpzZKC/d1Wi0k2z+uF0aqtqp9nBINwW8VFRJkA"
              crossOrigin="anonymous"/>
    </head>
    <body className={'layout-fixed sidebar-expand-lg bg-body-tertiary app-loaded sidebar-collapse'}>
    <div className={'app-wrapper'}>
      <Header/>
      <Sidebar/>
      <main className={'app-main'}>
        <ContentHeader/>
        <div className={"app-content"}>
          <div className={"container-fluid"}>
            {children}
          </div>
        </div>
      </main>
      <Footer/>
    </div>
    <Script src="https://cdn.jsdelivr.net/npm/overlayscrollbars@2.3.0/browser/overlayscrollbars.browser.es6.min.js"
            strategy="lazyOnload"/>
    <Script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" strategy="lazyOnload"/>
    <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" strategy="lazyOnload"/>
    <Script src="/js/adminlte.js" strategy="lazyOnload"/>
    </body>
    </html>
  );
}
